### ISSUE TITLE
Louvain算法只返回了_id和_louvain，社区内部的节点ID没返回

### ISSUE THREAD

**Issue by frankawp** [vesoft-inc/nebula-spark-utils#103]

**Comment by frankawp** [comment]
![企业微信截图_16251423586092](https://user-images.githubusercontent.com/1387130/124124881-8d4f9d80-daab-11eb-8101-ee2619b36e6c.png)

![企业微信截图_16251423193640](https://user-images.githubusercontent.com/1387130/124124952-a22c3100-daab-11eb-980d-a6950acad748.png)


![企业微信截图_16251337175200](https://user-images.githubusercontent.com/1387130/124124959-a5272180-daab-11eb-8746-45ebadc46b9e.png)


![企业微信截图_16251336712331](https://user-images.githubusercontent.com/1387130/124124967-a8221200-daab-11eb-849e-38895f2c6075.png)

**Comment by frankawp** [comment]
只返回了vId和cId？ 如果需要取invverVertices还有degree应该怎么做呢？

**Comment by QingZ11** [comment]
为了避免两处作答造成可能的信息不对成，这个问题以论坛的回复为主哈，图计算的同学将在论坛对你的问题作出回复，参见帖子 https://discuss.nebula-graph.com.cn/t/topic/4701
