### ISSUE TITLE
[Question] how could I split the graph into subgraphs according to cluster id?

### ISSUE THREAD

**Issue by CoinCheung** [vesoft-inc/nebula-spark-utils#125]
Hi,

Thanks for this great work!!

I tried some cluster algorithm and generate cluster id for each vertex. Now I need to compute betweenness centrality of on each cluster(because the whole graph is too large). But I do not know how to generate subgraphs according to the cluster ids, and how could I compute betweenness centrality in parallel on each subgraph. 

Would you please tell me how could I make this work?

**Comment by wey-gu** [comment]
@Nicole00 could you please help with this?
Thanks!

**Comment by Nicole00** [comment]
> Hi,
> 
> Thanks for this great work!!
> 
> I tried some cluster algorithm and generate cluster id for each vertex. Now I need to compute betweenness centrality of on each cluster(because the whole graph is too large). But I do not know how to generate subgraphs according to the cluster ids, and how could I compute betweenness centrality in parallel on each subgraph.
> 
> Would you please tell me how could I make this work?

If you have generated cluster if for each vertex, you can get subgraph using Graphx's `subgraph` interface:
```
graph.subgraph(vpred)
```
