### ISSUE TITLE
vertex is null exception

### ISSUE THREAD

**Issue by liganggit** [vesoft-inc/nebula-spark-utils#131]
when data source vertex is null, exchange have not a good warning but just a exception like 'java.lang.NullPointException'.when data source is not strict,someone do not know why and how to fix it.

**Comment by Nicole00** [comment]
> when data source vertex is null, exchange have not a good warning but just a exception like 'java.lang.NullPointException'.when data source is not strict,someone do not know why and how to fix it.

can you show more exception information please? 
In Exchange, if your vertex id or edge source id/ target id is null,  it won't pass the check, and the program will print `vertexId must exist and cannot be null, your row data is $row` log.

**Comment by liganggit** [comment]
thank you for your reply! that is all right. I saw the newest code.
