### ISSUE TITLE
update guava version?

### ISSUE THREAD

**Issue by everywan** [vesoft-inc/nebula-spark-utils#80]
v14 is too old!

can we update guava version like exchange1.0? just need replace 'getHostText' to 'getHost'.

[exchange 1.0 update guava pr](https://github.com/vesoft-inc/nebula-java/pull/241/files)

**Comment by Nicole00** [comment]
> v14 is too old!
> 
> can we update guava version like exchange1.0? just need replace 'getHostText' to 'getHost'.
> 
> [exchange 1.0 update guava pr](https://github.com/vesoft-inc/nebula-java/pull/241/files)

Do you mean update nebula client's guava version? Exchange does not import guava dependency， just used client's guava.

**Comment by everywan** [comment]
> > v14 is too old!
> > can we update guava version like exchange1.0? just need replace 'getHostText' to 'getHost'.
> > [exchange 1.0 update guava pr](https://github.com/vesoft-inc/nebula-java/pull/241/files)
> 
> Do you mean update nebula client's guava version? Exchange does not import guava dependency， just used client's guava.

The way of exchange use guava is not right. like [`getHostText`](https://github.com/vesoft-inc/nebula-spark-utils/blob/v2.0/nebula-exchange/src/main/scala/com/vesoft/nebula/exchange/GraphProvider.scala#L29), should be `getHost`

**Comment by everywan** [comment]
And need update the jar package on mirrors, too.

**Comment by Nicole00** [comment]
For now, exchange uses client's guava, whose version is v14.0, so the right way to get address's host is `getHostTest`. If guava's version is updated to 23, then the way should be modified to `getHost`.

But what's point is Exchange does not import guava additionally. So we will test and upgrade client's guava version first.

**Comment by everywan** [comment]
> For now, exchange uses client's guava, whose version is v14.0, so the right way to get address's host is `getHostTest`. If guava's version is updated to 23, then the way should be modified to `getHost`.
> 
> But what's point is Exchange does not import guava additionally. So we will test and upgrade client's guava version first.

Get it. thanks
